export {
  ControlCenter,
  Reservations,
  Delivery,
  Catering,
  Privatisations,
  SocialMedia,
  Billing,
  ProfileIcon,
  ProfileBasicInfo,
  ProfileContact,
  ProfileOpeningHours,
  ProfilePicturesAndMenus,
  ProfileAdditionaInfo,
  ProfileMembers,
  Subscriptions,
  SettingsIcon,
  SettingsPassword,
  BackArrow,
  LiveStream,
  Hamburger,
  SettingsBasicInfo,
  SettingsLogout,
  Integrations,
  Wholesalers,
  Restaurant,
  Dashboard,
  IntegrationHub,
  MenuManagement,
  Payments,
  Bookings,
  PrivateEvents,
  Reviews,
  Detectives,
  CommunityManagement,
  Marketing,
  Clients,
  StockManagement,
  Photography,
  DeliveryManagement,
  Analytics,
  ChevronDown,
  DropdownArrow,
  AppManager,
  Payroll,
  FoodWaste,
  PresenceManagement,
  CustomerLoyalty,
  EventsManagement,
  InfluencerManagement,
  CustomerSupport,
  OperationalReport,
  Intelligence,
  Fork,
  Adv,
  Pocket,
  Timer
} from "./navigation";
export {
  Docs,
  Feedback,
  Notifications,
  ExpandIcon,
  ExpandIconRestyled,
  SidebarExpandIcon,
  SearchIcon,
  CloseIcon,
  UploadFileIcon,
  CircleWarningIcon,
  Arrow,
  ArrowDown,
  AcceptedDetectiveIcon,
  BellIcon,
  WatchVideosIcon,
  MainInfoIcon,
  InfoIcon
} from "./mainControls";
export {
  Orders,
  Time,
  Menu,
  Price,
  Clock,
  Location,
  Pause,
  RejectModalIcon,
  StopOrdersModalIcon,
  WarningIcon
} from "./lefoodNavigation";

export { Globe, ChevronDownIcon } from "./footer";

export { ClockIcon, HeartIcon, CartIcon } from "./supplier";
