version: "3.4"
services:
  front:
    image: ${IMAGE}
    hostname: "sherlock.integration.front"
    command: ash -c 'yarn build && yarn start'
    labels:
      - "netguru.appname=sherlock"
      - "netguru.stage=integration"
    environment:
      - NODE_ENV=integration
      - APP_URL=VIRTUAL_HOST
      - VIRTUAL_HOST
      - PUBLIC_API_URL
      - PUBLIC_FOODETECTIVE_URL
      - STAGING_FOODETECTIVE_URL
      - PROD_FOODETECTIVE_URL
      - NETGURU_DEV_PASSWORD
      - OAUTH_CALLBACK_URL
      - OAUTH_PUBLIC_CLIENT_ID
      - OAUTH_SECRET_CLIENT_ID
      - PUBLIC_PUSHER_APP_KEY
      - PUBLIC_PUSHER_APP_CLUSTER
      - STRIPE_CLIENT_ID
      - PUBLIC_STRIPE_API_KEY
      - PUBLIC_GOOGLE_ANALYTICS_ID
      - PUBLIC_GOOGLE_MAPS_API_KEY
      - STAGING_AUTH
      - COMMUNITY_MANAGEMENT_TYPEFORM_ID
      - MARKETING_TYPEFORM_ID
      - PHOTOGRAPHY_TYPEFORM_ID
      - ROLLBAR_ACCESS_TOKEN
      - PLANS_BUSINESS_EXAMPLE_LINK
      - PARTOO_SDK_URL
      - GOOGLE_ADS_ID
      - GOOGLE_ADS_DEMO_BUTTON_EVENT_ID
      - GOOGLE_ADS_PAGE_VIEW_EVENT_ID
      - NEWSLETTER_GOOGLE_SHEET_ID
      - GOOGLE_SHEET_SERVICE_ACCOUNT_EMAIL
      - GOOGLE_SHEET_SERVICE_ACCOUNT_KEY
      - ALGOLIA_ENVIRONMENT
    networks:
      - frontend
    expose:
      - "3000"

networks:
  frontend:
    external:
      name: frontend
