version: "3.4"
services:
  sherlock:
    image: ${IMAGE}
    hostname: "sherlock.staging.front"
    command: ash -c 'yarn build && yarn start'
    restart: unless-stopped
    env_file:
      - /var/efs/secrets/sherlock.env
    networks:
      - frontend
    expose:
      - "3000"

networks:
  frontend:
    external: true
