version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
  aws-ecr: circleci/aws-ecr@7.3.0

references:
  deploy: &deploy
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.3

  node_machine: &node_machine
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.2.0

jobs:
  checkout_code:
    <<: *node_machine
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  yarn_lint:
    <<: *node_machine
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn -
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
      - run:
          name: Run JS linter
          command: yarn lint:js
      - run:
          name: Run CSS Linter
          command: yarn lint:css

  build_image_staging:
    <<: *node_machine
    steps:
      - run:
        # we need to overwrite default AWS_ credentials
        # because they exists in CircleCI
          name: "set ENV for deploying staging"
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$NEW_STAGING_AWS_ACCESS_KEY_ID' >> $BASH_ENV;
            echo 'export AWS_SECRET_ACCESS_KEY=$NEW_STAGING_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV;
            source $BASH_ENV
      - aws-ecr/build-and-push-image:
          aws-access-key-id: NEW_STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: NEW_STAGING_AWS_SECRET_ACCESS_KEY
          region: NEW_STAGING_AWS_DEFAULT_REGION
          account-url: NEW_STAGING_AWS_ECR_ACCOUNT_URL
          repo: foodetective-staging-sherlock
          tag: ${CIRCLE_SHA1}
          dockerfile: docker/Dockerfile.staging
          setup-remote-docker: true

  deploy_staging:
    working_directory: ~/repo
    executor: aws-cli/default
    steps:
      - checkout
      - run:
        # we need to overwrite default AWS_ credentials
        # because they exists in CircleCI
          name: "set ENV for deploying staging"
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$NEW_STAGING_AWS_ACCESS_KEY_ID' >> $BASH_ENV;
            echo 'export AWS_SECRET_ACCESS_KEY=$NEW_STAGING_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV;
            source $BASH_ENV
      - run:
          name: Prepare ENV vars
          command: |
            echo IMAGE=${NEW_STAGING_AWS_ECR_ACCOUNT_URL}/foodetective-staging-sherlock:${CIRCLE_SHA1} > codedeploy/parameters
      - aws-cli/setup:
          aws-access-key-id: NEW_STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: NEW_STAGING_AWS_SECRET_ACCESS_KEY
          aws-region: NEW_STAGING_AWS_DEFAULT_REGION
      - aws-code-deploy/push-bundle:
          application-name: foodetective-staging-sherlock
          bundle-bucket: foodetective-staging-codedeploy
          bundle-key: sherlock/$CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1
      - aws-code-deploy/deploy-bundle:
          application-name: foodetective-staging-sherlock
          deployment-group: foodetective-staging-sherlock-group
          bundle-bucket: foodetective-staging-codedeploy
          bundle-key: sherlock/$CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1

  build_push_docker:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install AWSCLI
          command: sudo pip install awscli
      - run:
          name: Log into ECR
          command: $(aws ecr get-login --no-include-email --region eu-central-1)
      - run:
          name: Build docker image
          command: docker build --build-arg OAUTH_CALLBACK_URL --build-arg APP_URL --build-arg OAUTH_PUBLIC_CLIENT_ID --build-arg PUBLIC_FOODETECTIVE_URL --build-arg OAUTH_SECRET_CLIENT_ID --build-arg PUBLIC_API_URL --build-arg PUBLIC_GOOGLE_MAPS_API_KEY --build-arg PUBLIC_PUSHER_APP_CLUSTER --build-arg PUBLIC_PUSHER_APP_KEY --build-arg STRIPE_CLIENT_ID --build-arg PUBLIC_STRIPE_API_KEY --build-arg PUBLIC_GOOGLE_TAG_MANAGER_ID --build-arg PUBLIC_FACEBOOK_PIXEL_ID --build-arg PUBLIC_GOOGLE_ANALYTICS_ID --build-arg PUBLIC_FOODETECTIVE_URL --build-arg COMMUNITY_MANAGEMENT_TYPEFORM_ID --build-arg MARKETING_TYPEFORM_ID --build-arg PHOTOGRAPHY_TYPEFORM_ID --build-arg ROLLBAR_ACCESS_TOKEN --build-arg PLANS_BUSINESS_EXAMPLE_LINK --build-arg LINKEDIN_ADS_ID --build-arg PARTOO_SDK_URL --build-arg GOOGLE_ADS_ID --build-arg GOOGLE_ADS_DEMO_BUTTON_EVENT_ID --build-arg GOOGLE_ADS_PAGE_VIEW_EVENT_ID --build-arg NEWSLETTER_GOOGLE_SHEET_ID --build-arg GOOGLE_SHEET_SERVICE_ACCOUNT_EMAIL --build-arg GOOGLE_SHEET_SERVICE_ACCOUNT_KEY -t ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-${CIRCLE_SHA1} -f docker/Dockerfile.production .
      - run:
          name: Push image to AWS ECR
          command: |
            docker tag ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-${CIRCLE_SHA1} ${AWS_ECR_REPO_URL_BUSINESS}:latest
            docker tag ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-${CIRCLE_SHA1} ${AWS_ECR_REPO_URL_BUSINESS}:${CIRCLE_SHA1}
            docker push ${AWS_ECR_REPO_URL_BUSINESS}:latest
            docker push ${AWS_ECR_REPO_URL_BUSINESS}:${CIRCLE_SHA1}

  deploy_production_front:
    <<: *deploy
    working_directory: ~/repo/deployment
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: bundle config
          command: bundle config --local path ~/repo/deployment/vendor/bundle
      - run:
          name: Install AWSCLI
          command: |
            sudo apt install -qq -y python python-pip python-dev
            sudo pip install awscli==1.19.23
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy to production
          command: |
            $(aws ecr get-login --no-include-email --region eu-central-1)
            bundle install; bundle exec cap production deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code

      ###   STAGING   ###
      - build_image_staging:
          requires:
            - checkout_code
          filters:
            branches:
              only: master
      - deploy_staging:
          requires:
            - build_image_staging
          filters:
            branches:
              only: master

      ###   PRODUCTION   ###
      - build_push_docker:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - production
                - production-setup
      - deploy_production_front:
          requires:
            - checkout_code
            - build_push_docker
          filters:
            branches:
              only:
                - production
                - production-setup
