FROM node:10-alpine

ENV APP_HOME /app
ENV PATH $PATH:$APP_HOME/node_modules/.bin

RUN env

## Copy build/ folder to new image
ADD . $APP_HOME
WORKDIR $APP_HOME

RUN yarn install
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
