FROM node:14.2.0-alpine

ENV APP_HOME /app
ENV PATH $PATH:$APP_HOME/node_modules/.bin

## Copy build/ folder to new image
ADD . $APP_HOME
WORKDIR $APP_HOME

RUN yarn install
EXPOSE 3000
CMD ["yarn", "start"]
