version: '3.7'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    restart: always
    environment:
      DEFAULT_HOST: "{{ default_host | default('localhost') }}"
    labels:
      - netguru.appname=netguru-frontpage
      - netguru.stage=staging
    ports:
      - "80:80"
    volumes:
      - ./conf.d/001-healthcheck.conf:/etc/nginx/conf.d/001-healthcheck.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d/htpasswd:/etc/nginx/htpasswd/sherlock.calluna.devguru.co
    networks:
      - frontend

networks:
  frontend:
    external: true
