version: '3.7'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    restart: always
    environment:
      DEFAULT_HOST: "{{ default_host | default('localhost') }}"
    labels:
      - netguru.appname=netguru-frontpage
      - netguru.stage=staging
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d
    networks:
      - frontend

networks:
  frontend:
    external: true
