#!/bin/bash

# Treat unset variables and parameters [...] as an error when performing parameter expansion (substituting).
set -u
# Print a trace of simple commands
set -x

cd /opt/codedeploy-agent/deployment-root/"${DEPLOYMENT_GROUP_ID}"/"${DEPLOYMENT_ID}"/deployment-archive || exit 1

if [[ "$APPLICATION_NAME" == "foodetective-staging-sherlock" ]]; then
  source codedeploy/start_server_staging
else
  exit 1
fi
