#!/bin/bash

# Treat unset variables and parameters [...] as an error when performing parameter expansion (substituting).
set -u
# Print a trace of simple commands
set -x

cd /opt/codedeploy-agent/deployment-root/"${DEPLOYMENT_GROUP_ID}"/"${DEPLOYMENT_ID}"/deployment-archive || exit 1

# application
# shellcheck disable=SC2046,SC2002
export $(cat codedeploy/parameters | xargs)

# login to ECR
$(aws ecr get-login --region eu-central-1 --no-include-email)

# !!! NGINX is deployed from thefoodetective-front repository !!!

docker-compose -p sherlock -f docker-compose-staging.yml up -d --force-recreate

# Remove unused data, do not prompt for confirmation
docker system prune --all --force
