export { default as Navigation } from "./Navigation";
export { default as TopSection } from "./TopSection";
export { default as Services } from "./Services";
export { default as Plans } from "./Plans";
export { default as Cooperations } from "./Cooperations";
export { default as Features } from "./Features";
export { default as Testimonials } from "./Testimonials";
export { default as Widget } from "./Widget";
export { default as DevelopersAndApi } from "./DevelopersAndApi";
